name: Build on Push to Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build ./src/ -c Release
