name: Preview Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack ./src/ -c Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push BrandonAlexander.ProjectTemplates.WebApiJwt.${VERSION}.nupkg --source nuget.org --api-key ${NUGET_ORG_API_KEY}
      env:
        NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
